name: enigma
description: A minimal package for basic cryptographic operations in Dart.
version: 1.0.0
publish_to: none
repository: https://github.com/carlosmakin/enigma.git

environment:
  sdk: ^3.2.5

dependencies:
  pointycastle: ^3.7.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1
