name: enigma
description: A minimal package for basic cryptographic operations in Dart.
version: 1.0.0
publish_to: none
repository: https://github.com/carlosmakin/enigma.git

environment:
  sdk: ^3.1.5

dependencies:
  pointycastle: ^3.7.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
